### ISSUE TITLE
Add support for plain color backgrounds

### ISSUE THREAD

**Issue by grahammcculloch** [sillsdev/bible-karaoke#1]
...rather than image backgrounds.

User could select from a color palette in the UI and the rendering code would use that instead.

**Comment by kklcclkk** [comment]
I appreciate this feature. Thank you. One idea to make it even more useful for the average user who does not know how to look up number codes for colors or even that they exist:

(a.) Add a few more color options to the current ones (my team would like some in the browns/natural colors range if possible)
or 
(b.) Add a way to access a palette selector that already exists in Windows (I seem to notice a number of programs pull from a similar selector that looks something like this:
![image](https://user-images.githubusercontent.com/61860910/76055618-b8ed7100-5fa6-11ea-9688-27b88112970c.png)


(screenshot from LibreOffice)

**Comment by megahirt** [comment]
Pretty sure this is completed in 241d570cf7840f6e752491c799e02bfc92355bcb.  I will open another issue for the color picker
