### ISSUE TITLE
Use chrome.exe that is bundled with node_modules/puppeteer

### ISSUE THREAD

**Issue by megahirt** [sillsdev/bible-karaoke#16]
When I try to generate a video, I get this error:

Could not find Chrome

Error: Could not find Chrome at module.exports.record (C:\Users\Samsung\AppData\Local\Programs\bible-karaoke\resources\app.asar\build\cli\lib\rendering\record-frames.js:10:15) at processTicksAndRejections (internal/process/task_queues.js:85:5) at async render (C:\Users\Samsung\AppData\Local\Programs\bible-karaoke\resources\app.asar\build\cli\lib\rendering\render-frames.js:45:5)

Does that mean Chrome is a prerequisite for Bible Karaoke? I don't have it installed, but use it as a portable app from a Veracrypt hidden container, for security reasons.

W

**Comment by megahirt** [comment]
We need to test BK on a machine that doesn't have Chrome installed.  Or at least installed normally.

**Comment by kklcclkk** [comment]
For the error message if someone doesn't have Chrome installed, I'd suggest something like 
"Error: You must install Google Chrome" and give a link to the Chrome download page (if that's allowed)
or "Please install Google Chrome in order to use Bible Karaoke software" and give a link to the download page
or something like that.

**Comment by megahirt** [comment]
confirmed that current version of BK doesn't work if the user doesn't have chrome installed.  This issue is about making BK function with the version of chrome.exe that is already delivered with puppeteer.  Bonus points if there is some way to use chrome.exe that is shipped with Electron (not sure if that's even possible because I couldn't locate it).

On my windows machine, chrome.exe delivered with puppeteer is located here:
C:\Users\Chris\AppData\Local\Programs\bible-karaoke\resources\app.asar.unpacked\node_modules\puppeteer\.local-chromium\win64-706915\chrome-win\chrome.exe

**Comment by echu888** [comment]
@irahopkinson Could I request your help?  I'm still not able to perform Windows builds.  Can you try out the branch feature/useEmbeddedChromium and let me know whether or not it resolves this issue?

**Comment by megahirt** [comment]
I have been working to get a Win10 VM up and working.  Just succeeded in installing BK 0.3.1 with no Chrome installed and got the expected "could not fine Chrome" error.

![image](https://user-images.githubusercontent.com/3444521/79810418-34f81880-839d-11ea-9e29-4bd0a426c8c1.png)

Now I will build and install from your branch...

**Comment by megahirt** [comment]
I built your branch @echu888 and ran into a different problem related to the logger which I will post in Slack.

**Comment by echu888** [comment]
We should check if there is any effect on the size of the binary after this change.

**Comment by echu888** [comment]
Information regarding [using puppeteer with the browser bundled with electron](https://github.com/puppeteer/puppeteer/issues/4655)
