### ISSUE TITLE
ffmpeg, ffprobe, chrome and all related dependencies should be included in the installer

### ISSUE THREAD

**Issue by megahirt** [sillsdev/bible-karaoke#18]
The current code uses a run-time downloader to download missing dependences.  This is great in theory, but we need to guarantee that the program can run offline once it is installed.  The installer should include ffmpeg and ffprobe dependencies from the get-go.

See #11 and #16

**Comment by megahirt** [comment]
We need to change our usage of https://www.npmjs.com/package/ffbinaries to download these as a build step.

**Comment by echu888** [comment]
ffmpeg and ffprobe are included in the install now.  Chrome is not.  Since it already bundles electron, should investigate using that instead of having to include two browsers.

**Comment by echu888** [comment]
Just saw the note on the other bug ... will look into the possibility of using the version of chrome that is packaged with puppeteer.

**Comment by megahirt** [comment]
Great thank you!

**Comment by megahirt** [comment]
done and shipped in 0.3.1
