### ISSUE TITLE
UI - Make horizontal section header wider and clickable

### ISSUE THREAD

**Issue by kklcclkk** [sillsdev/bible-karaoke#19]
In the user interface, it would be helpful if the area in which you can click around the words "1. HearThis" and "2. Display" would span the entire length of the window area (up to or even including the check mark that appears there after proceeding to "Next". 

Note: this issue is MUCH lower priority than getting bold section headings and adjusting the animation, and for that reason I hesitated to even add it as an issue.

**Comment by megahirt** [comment]
Yes there are some UI issues around section 1 and section 2.  I would rather redesign the UI to support additional features, and this redesign should not introduce scrollable areas.  Instead, we should try and make the UI be responsive within reason.

**Comment by kklcclkk** [comment]
I'm sorry, I think was not very precise in my original post. I meant wider from left to right, not longer from top to bottom.
In the screenshot below I have circled the currently clickable area and drawn and arrow in the area I would like to be clickable (click to expand).
![image](https://user-images.githubusercontent.com/61860910/76180491-b5e5c100-61f0-11ea-9911-5f688b74f99e.png)

**Comment by megahirt** [comment]
OK I understand now what you're saying.  This should be a small fix so we will see if that can be done.
