### ISSUE TITLE
Add support for selecting font color

### ISSUE THREAD

**Issue by grahammcculloch** [sillsdev/bible-karaoke#2]
Especially useful if the background color is set (#1)

**Comment by megahirt** [comment]
I don't know if font color is actually needed any more?  Should we support this?

**Comment by kklcclkk** [comment]
Yes, font color is needed. This has already been added and it is sufficient. Ideally it would allow selection from the same color palette as the background selection will (eventually when that capability is added). But for now it is usable and sufficient for my team's needs.

**Comment by megahirt** [comment]
Closed as implemented in v0.3.0
