### ISSUE TITLE
Chapter number announcement in local language

### ISSUE THREAD

**Issue by kklcclkk** [sillsdev/bible-karaoke#20]
I think this was determined to be an issue that needed to be dealt with by the HearThis team, technically, but I am putting it here because it is something that needs to be dealt with in order to make the UI ready for use by the average computer user. And in case there is a possibility that it could be dealt with by BK instead.
The word "chapter" is pulled from somewhere within HearThis. However, the speaker of the local language announces this in their own language. It isn't a problem in SAB because there is no word "Chapter" that appears, but in the video that is output from Bible Karaoke, "Chapter {1}" appears in English. 
I like the fact that the text appears at all, we just need to figure out how to make it easier for it to appear in the local language.

**Comment by megahirt** [comment]
@kklcclkk Shouldn't we just omit the word "chapter" and just display a big numeral, like 1, 2, 3?  Would this fix it?  If the speaker reads "chapter 1" in the local language, it shouldn't be a problem to see just "1".  What do you think?

**Comment by kklcclkk** [comment]
Yes, I think that would fix it. Great idea.

**Comment by Hiro-Nakamura** [comment]
It would be helpful if I could see the HearThis output that includes the "Chapter" title.  we can look at how to automatically remove that for you.

**Comment by kklcclkk** [comment]
Do you want a screenshot of the video file that BK output that includes the word "Chapter" at the beginning? Or a screenshot of the part of HearThis where we see the word "Chapter _"?

**Comment by kklcclkk** [comment]
![image](https://user-images.githubusercontent.com/61860910/76496139-f3558300-646a-11ea-871e-3a096d32bd7e.png)
Here is what it looks like in my video

**Comment by kklcclkk** [comment]
What would be really great is if HearThis would ask the user how to say "Chapter" in their language and then it would use that word every time in the prompts (and then could somehow be pulled through to BK). But that would require some programming on the HearThis side.

**Comment by megahirt** [comment]
@kklcclkk yeah, we aren't going to involve any HearThis programming at this point in time.  I think we will attempt to remove the word "Chapter" from the output

**Comment by Hiro-Nakamura** [comment]
can you look in the Ephesian chapter 2 folder, and send me the info.xml file for that.

It should look something like this in the folder structure:
<img width="910" alt="folderLayout" src="https://user-images.githubusercontent.com/3666960/76500060-6f9f9480-6472-11ea-8aa2-9a55d7161f4c.png">

**Comment by megahirt** [comment]
@Hiro-Nakamura I found where the chapter is coming from.  It's in the info.xml file for Collosians chapter 1

```
<ChapterInfo Number="1">
  <Recordings>
    <ScriptLine>
      <LineNumber>1</LineNumber>
      <Text>Chapter 1</Text>
      <RecordingTime>2019-09-27T03:56:59.6484552Z</RecordingTime>
      <Verse>0</Verse>
      <Heading>true</Heading>
      <HeadingType>c</HeadingType>
    </ScriptLine>
    <ScriptLine>
      <LineNumber>2</LineNumber>
      <Text>Tamangaò̌ raò̌rî rî̌kaò̌</Text>
      <RecordingTime>2019-09-27T03:57:13.2196834Z</RecordingTime>
      <Verse>0</Verse>
      <Heading>true</Heading>
      <HeadingType>s</HeadingType>
    </ScriptLine>

```

**Comment by megahirt** [comment]
I am now uploading the project data to Google Drive

**Comment by Hiro-Nakamura** [comment]
Sorry, didn't see a Colossians in the developers resources on the Google Drive.  Can you post a link here?

Also, it looks like the definition includes a ```<LineNumber>1</LineNumber>``` setting for the chapter title.  And the rest of the entries follow after that.  Does that mean the XXX.wav files start at 1?  or do they still start at 0?

**Comment by megahirt** [comment]
Sorry about that.  My upload failed yesterday.  I'm uploading again now.  You will find it at Developer Resources/HearThis projects/N***/Colossians/1

**Comment by megahirt** [comment]
@Hiro-Nakamura it looks like it's available on Google Drive now.  Thanks for pursuing this.
