### ISSUE TITLE
Test BK with plain Windows 10 install

### ISSUE THREAD

**Issue by megahirt** [sillsdev/bible-karaoke#28]

**Comment by hahn-kev** [comment]
Should be pretty easy to test using Windows Sandbox (only in windows 10 pro)

**Comment by megahirt** [comment]
Thanks!  that's good to know.  From our testing on Thursday, the BK
installer will fail on plain Windows 10 because it has a dependency on
chrome.exe being installed.  It would be neat to figure out if we could
leverage the electron chrome.exe (if one exists) to make this thing work
self contained without the external dependency.  Same for ffmpeg.  I
learned that electron actually comes with ffmpeg included, it's just that
we aren't accessing it and requiring a separate version to be downloaded
and distributed.

Warm regards,

Christopher Hirt
Team Manager - Thailand
SIL Language Software Development
chris_hirt@sil.org

**Comment by megahirt** [comment]
closing
