### ISSUE TITLE
Add support for 'Intro' material

### ISSUE THREAD

**Issue by grahammcculloch** [sillsdev/bible-karaoke#3]
> I tried out our recordings of Colossians, which HearThis numbers 0 (for the introductory material that is not part of the Bible), 1 (for chapter 1), 2, 3, and 4 (for chapters 2, 3, 4). Bible Karaoke numbers them 1-5 and no 0. I anticipate this being confusing for users. They might want to make a video of chapter 3, so they choose "3" but then they end up with a video that just contains chapter 2, and can't figure out why. If there would be a work-around that would allow what HearThis calls "0" to be labelled as "Intro" or "Introduction" or even "0" and the other chapters to be numbered 1-4, that would be really helpful.

**Comment by megahirt** [comment]
@kklcclkk is this still an issue?

**Comment by kklcclkk** [comment]
This seems to be resolved and working fine. Thanks!

**Comment by megahirt** [comment]
Closing as fixed v0.3.0
