### ISSUE TITLE
Phantom text appearing in video - related to lack of chapter announcement

### ISSUE THREAD

**Issue by kklcclkk** [sillsdev/bible-karaoke#58]
In the Ephesians video output from 0.3.3, I initially tried chapter 5 but got an error, so I switched to chapter 3. The resulting video for chapter 3 contains the section heading and the first verse from chapter 5, then continues on with chapter 3. The audio only is chapter 3 audio. 

Kudos -- The karaoke highlighting animation does a pretty good job of figuring out within a few words that the initial text is not right, and skips down to the correct text.

**Comment by kklcclkk** [comment]
I also have a case of making a video for Colossians and some text from Ephesians ch 5 is randomly at the beginning of the video.

**Comment by jamesduncan** [comment]
Did you by any chance create a video before that one without closing Bible Karaoke? If so I think Johnny is working on a fix for that. If not let me know and we will try to reproduce and figure out what went wrong. 

James Duncan

**Comment by kklcclkk** [comment]
Yes, it is the same problem. Glad to hear it is being worked on. In the mean time I will just close the program in between each video.

**Comment by irahopkinson** [comment]
Fixed in v0.3.4
