### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by oxr463** [sillsdev/bible-karaoke#6]
There is a lot of great software [on here](https://github.com/sillsdev), but screenshots or videos would be helpful to see how it works or what it does.

**Comment by megahirt** [comment]
Hi oxr463, thank you for your comment.  Our published software is more or less located over at https://software.sil.org

This particular software, Bible Karaoke, is alpha software and you can learn more about it over at http://biblek.info  It may eventually move over to software.sil.org once it becomes more mature.
