### ISSUE TITLE
BK not pulling the same text as HearThis

### ISSUE THREAD

**Issue by kklcclkk** [sillsdev/bible-karaoke#61]
I am getting different text in my video than what I see in HearThis. The text in the BK video is older, outdated, and contains lots of spelling errors that have since been fixed in Paratext, which is where HearThis is pulling from.

**Comment by megahirt** [comment]
Is there a way to "refresh" or "sync" with Paratext from inside HearThis?

Kind regards,

Chris

**Comment by kklcclkk** [comment]
Not that I know of. That is all automatic as far as I can tell. Best to ask @tombogle

**Comment by megahirt** [comment]
I would assume that if the text in HearThis is correct, that the text is
accurately reflected in the internal files (info.xml) in the HearThis
program directory, but yes Tom Bogle could help explain.
Warm regards,

Christopher Hirt
Team Manager - Thailand
SIL Language Software Development
chris_hirt@sil.org

**Comment by kklcclkk** [comment]
I have added @tombogle to the Paratext project to see if he can diagnose what it going on

**Comment by megahirt** [comment]
we've basically diagnosed this as a HT -> BK interaction problem that is partially user related.  Won't fix. and Closing.
